# Generated by Django 5.1.6 on 2025-02-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='can_data_be_shared',
            new_name='data_can_be_shared',
        ),
    ]
