# Generated by Django 5.1.6 on 2025-02-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_can_data_be_shared_customuser_data_can_be_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='data_can_be_shared',
            new_name='can_data_be_shared',
        ),
    ]
